SQLALCHEMY_DATABASE_URI = 'sqlite:///database.sqlite'
SECRET_KEY = 'F12Zr47j\3yX R~X@H!jmM]Lwf/,?KT'
SAVE_FOLDER = './files'
STATIC_FOLDER = '../../client/dist/static'
SQLALCHEMY_TRACK_MODIFICATIONS = 'False'
PORT = '3000'